### ISSUE TITLE
Project Critique: tributepage.html & tributepage.css

### ISSUE THREAD

**Issue by dariusstrasel** [wjbritton/tributePage#1]
Hi Will,

Thanks for submitting. Here is some feedback from my review:

**Highlights**
- Excellent use of the Bootstrap Carousel!
- Clean design; I like it.
- Resources such as CSS, and images are missing or not imported correctly.
-  HTML needs linting.

**Improvement:**
_tributepage.html_
- Line 7: The href value for your CSS import does not match the filename. When I load the page, I get a 404 due to the non-matching CSS.
- Lines 40, 44, 48: No images are included in the repo, and so these do not load.
- Line 108: This closing tag matches nothing; most likely a duplicate.
- Line 138: Extra bracket
- Lines 17-147:  Indentation is inconsistent. Child tags should always be indented under the parent tag, siblings should be equal. All tags are children of the body tag, and should be indented at least once.
Edit:
- The HTML tag does not have a closing tag.

_tributepage.css_
- Line 65: This rule-set is ill-formed. Check out documentation. As a note, I fixed the CSS import and wasn't able to see this.

I would recommend you always lint your files before submitting, or uploading to Github!

**Resources:**
Format Linter: https://dirtymarkup.com/
HTML Validator: https://validator.w3.org/
CSS Validator: https://jigsaw.w3.org/css-validator/
JS Validator: www.jslint.com/

**Comment by wjbritton** [comment]
Should be all set thank you for the feedback!

**Comment by dariusstrasel** [comment]
Awesome, congrats on the work! Looking forward to your other projects.

-Darius
